name: Arduino Checks

on: [push, pull_request]

jobs:
  lint:
    name: Arduino lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          path: ${{github.workspace}}/src/arduino-library/MidiDmxBridge/
          library-manager: update
          compliance: strict

  compile-examples:
    name: Arduino compile examples
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno
          - arduino:avr:pro
          - arduino:avr:leonardo
          - arduino:avr:mega

    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          verbose: true
          fqbn: ${{ matrix.fqbn }}
          libraries: |
            - source-path: ${{github.workspace}}/src/arduino-library/MidiDmxBridge/
          sketch-paths: |
            - 'src/arduino-library/MidiDmxBridge/examples/Basic_IO'
            - 'src/arduino-library/MidiDmxBridge/examples/DMXGain'
            - 'src/arduino-library/MidiDmxBridge/examples/DMXStaticScene'

  compile-production:
    name: Arduino compile production
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno
          - arduino:avr:pro
          - arduino:avr:leonardo
          - arduino:avr:mega

    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          verbose: true
          fqbn: ${{ matrix.fqbn }}
          libraries: |
            - source-path: ${{github.workspace}}/src/arduino-library/MidiDmxBridge/
            - name: DMXSerial
          sketch-paths: |
            - 'src/arduino-MidiDmxBridge'
